### PR TITLE
feat: parse and fetch metadata

### LINKED ISSUE #2: Add scheduled CI to retrieve github stars for all notebooks that have github links attached to them.
Could use: https://pygithub.readthedocs.io/en/latest/examples/Repository.html#get-count-of-stars

### PR DESCRIPTION
**Pull request by kjappelbaum**
Issue #2 mentions to have one folder per type. However, if you already just look at the examples this will not work all the time (what if you have all three?). Perhaps it is easiest to have either (1) one entry per URL (I do not like this due to duplicates), (2) accept multiple URLs for every entry but then use the first as major one (or some other rule)

closes #2 

ToDos:
- [ ] Discuss what we keep optional and if we enforce list for URL/type 
- [ ] Add tests to CI 
- [x] Add cron job

### CODE REVIEW

**Comment by duerrsimon** [comment]
Thanks! Only now found the time to look into this. 
Adding some of the examples I realized that there might be notebooks available on colab and binder simultaneously. I think it is therefore best to handle the different types in the markdown file and not via folders.
So all notebooks sit in `content/notebooks`. 
See this example: https://raw.githubusercontent.com/colab-db/colab-db.github.io/main/content/notebooks/rdkit-etkdg.md
With this we have no duplicates and can show both links in the UI. The user can then choose what they prefer.

**Comment by kjappelbaum** [comment]
>Adding some of the examples I realized that there might be notebooks available on colab and binder simultaneously. I think it is therefore best to handle the different types in the markdown file and not via folders.
So all notebooks sit in content/notebooks.

i think this is what I assumed ;)

**Comment by duerrsimon** [comment]
Finally was able to finish most of the ui stuff. did you make any progress on the validation, extraction of stars?

**Comment by kjappelbaum** [comment]
the main missing part is the action, the scripts themselves are done (assuming that the schema used in the UI is aligned to the things we assume in the pydantic schema)

**Comment by duerrsimon** [comment]
I checked the test notebooks in the pull request and those match the specification of the notebooks now used for generating the content. 

Let me know if I can be of assisstance. I have not added the stars into the code yet (currently just dummy values). I guess the easiest would be if your scheduled action would write them to a json file with the filename of the `*.md` as key and the number of stars as the value.

**Comment by kjappelbaum** [comment]
Will be able to come back to it after the ACS meeting. If you want to get it out earlier, don't feel the need to wait for me and just go ahead

**Comment by duerrsimon** [comment]
Any progress on this?

**Comment by kjappelbaum** [comment]
>Any progress on this?

nope, I'll have some time tomorrow though.

**Comment by kjappelbaum** [comment]
can I now assume that the data structure you consume in the js code is now the shape you want?

**Comment by duerrsimon** [comment]
yes! It's better to organize it centrally in one folder and use type to denote one or more platforms (colab, binder, hf)

**Comment by kjappelbaum** [comment]
I suggest we change the date format to something [more standard](https://pydantic-docs.helpmanual.io/usage/types/#datetime-types) such as `YYYY-MM-DD`. 

Will later check if the submission form also assumes this

**Comment by duerrsimon** [comment]
> I suggest we change the date format to something [more standard](https://pydantic-docs.helpmanual.io/usage/types/#datetime-types) such as YYYY-MM-DD.
Good point, currently this is not added on the form. Will add this to submit.vue to automatically populate it with the current date.

**Comment by duerrsimon** [comment]
Everything else looks great and I think its only failing cd and build because of lacking permissions. I will merge it. 
As I am wrapping up in the US at the moment I will only have time to finish everything once back to switzerland.

**Comment by duerrsimon** [comment]
Been quite busy so I didn't have much time working on this. I just merged your request,  fixed the dependency issue because nuxt v3 and content v2 are finally stable now and added a manual workflow trigger to `update-data.yml`. 

Think the only thing left to do is to incorporate `metadata.json` into the site

**Pull request merged**
